name: env-oracle
services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    hostname: oracle
    container_name: oracle
    environment:
      - TZ=America/Sao_Paulo
      - ORACLE_PWD=${ORACLE_PWD:-adm}
      - ORACLE_DB_NAME=${ORACLE_DB_NAME:-TEMPLATEBANKING}
    volumes:
      - ./database/oracle:/opt/oracle/scripts/startup
    ports:
      - "1521:1521"
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: "4GB"